### ISSUE TITLE
choc v1 and cherry MX

### ISSUE THREAD

**Issue by dhruvinsh** [duckyb/urchin#1]
Hi,
Is it possible to accommodate both switch types like Sweep does. I am looking for cherry MX along with choc v1 if possible.

**Comment by duckyb** [comment]
@dhruvinsh Sorry but this is currently out of the scope of this project. Adding support for more switches would make the repository and PCB much more complex and it's not something I'm interested in for the Urchin.

If you wish to add support for them yourself feel free to fork the repository and make the changes, I can give some advice if needed.

**Comment by dhruvinsh** [comment]
Make sense. Thank you. What is the best way to reach out to you? Are you available on discord?

**Comment by duckyb** [comment]
Yes you can find me on discord, this is my account:
![image](https://user-images.githubusercontent.com/27895007/216857260-16cf38cf-db9f-4f08-b07b-6fcfe341585e.png)

**Comment by dhruvinsh** [comment]
Thanks. Just send you a request.
