### ISSUE TITLE
36 keys layout

### ISSUE THREAD

**Issue by ajtakrajta** [duckyb/urchin#3]
Hi,
thanks for a great keyboard. Did you consider to create also a 36 keys layout similar to Swoop? I'm aware of sweep36 keyboards, but Urchin and Swoop have simply nicer PCB shape. I'm ready to order and test PCBs, but unfortunately I lack free time to modify PCB design itself.

**Comment by duckyb** [comment]
I don't have the time to maintain multiple versions of PCBs which is why I've decided to restrict this project to just one version
