### ISSUE TITLE
wired version?

### ISSUE THREAD

**Issue by lpanebr** [duckyb/urchin#7]
Any chance of my getting a wired version? 
Thanks!

**Comment by duckyb** [comment]
I'm not interested in providing a wired version, but anyone is welcome to fork this project. If you want a wired build I'd recommend the Sweep instead.

**Comment by duckyb** [comment]
Note:

Keep in mind that the keyboard can be used wired, even without a battery. But the two halves of the keyboard communicate via bluetooth only.

Adding a wired connection between the two halves (wired interconnect) is not supported by ZMK. But even if it was, I am not willing to develop and maintain two different versions of this keyboard.
