### ISSUE TITLE
Remove diode footprint from the top surface

### ISSUE THREAD

**Issue by ToppDev** [duckyb/urchin#8]
Following up on the comment in PR #5, I think this is better to discuss in an Issue first.

> ...
> Also I agree with moving the diodes now that they will be soldered on the bottom side, but the diodes on the top surface should be removed at the same time.
>
> _Originally posted by @duckyb in https://github.com/duckyb/urchin/issues/5#issuecomment-1973554221_

With removing the Diods on the top side, do you mean something like what was done in #6? (the right through hole could also be removed I think)
<img src='https://github.com/duckyb/urchin/assets/17766093/4f8fac34-fd25-400c-bb60-7d537d2c3dbc' width='400'>

If you are interested, I could start fresh from the current main and replace the diods. Result would look something like

<img src='https://github.com/duckyb/urchin/assets/17766093/9d2d8c81-c578-4bda-b99a-e4a010f25b97' width='500'>

**Comment by duckyb** [comment]
If it's done correctly in #6 I can just merge that. I just didn't make time to review it yet, that's my bad.
I have to setup kicad from scratch so I've been delaying it.

**Comment by ToppDev** [comment]
@Mathrocker666 sadly deleted his branch already. If he is still around and could reopen his PR that would be nice

**Comment by duckyb** [comment]
Restored in #9
